# Generated by Django 2.2 on 2020-11-17 14:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('summary', models.TextField()),
                ('lang', models.CharField(default='en', max_length=2)),
                ('category', models.CharField(default='news', max_length=30, null=True)),
                ('date_uploaded', models.DateField(default=datetime.datetime(2020, 11, 17, 14, 35, 26, 905357, tzinfo=utc))),
                ('text_vector', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SimilarArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('principal_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_articles', to='articles.Article')),
                ('related_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='articles.Article')),
            ],
        ),
    ]
