# Generated by Django 2.2 on 2020-11-17 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201117_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2020, 11, 17, 18, 44, 26, 791979, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='lang',
            field=models.CharField(default='en', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_vector',
            field=models.TextField(null=True),
        ),
    ]
