# Generated by Django 2.1.5 on 2021-06-06 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20201118_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2021, 6, 6, 20, 32, 54, 309990, tzinfo=utc)),
        ),
    ]
