# Generated by Django 2.2 on 2020-11-17 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 17, 18, 44, 26, 793837, tzinfo=utc)),
        ),
    ]
