# Generated by Django 2.2 on 2020-11-17 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20201117_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2020, 11, 17, 20, 25, 9, 809252, tzinfo=utc)),
        ),
    ]
